framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    session:
        handler_id: null
        cookie_secure: auto       # Utilise HTTPS si disponible
        cookie_httponly: true     # Empêche l'accès via JavaScript
        cookie_samesite: strict   # Politique SameSite pour les cookies de session
        # Note that the session will be started ONLY if you read or write from it.
        enabled: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file