framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    session:
        handler_id: null
        cookie_secure: auto       # Utilise HTTPS si disponible
        cookie_httponly: true     # Empêche l'accès via JavaScript
        cookie_samesite: strict   # Politique SameSite pour les cookies de session
        enabled: true             # Activer la gestion de session

    router:
        strict_requirements: null
        http_port: 80             # Port HTTP par défaut
        https_port: 443           # Port HTTPS par défaut

    trusted_proxies: '127.0.0.1, REMOTE_ADDR'  # Autoriser les proxies comme Heroku
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto']  # Gérer les en-têtes de sécurité

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file