security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\UserTabEntity
                property: mail

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_connexion
                check_path: app_connexion
                default_target_path: admin
                always_use_default_target_path: true
                failure_path: app_connexion
                enable_csrf: true
            logout:
                target: app_accueil

            # Ajout des en-têtes de sécurité HTTP
            headers:
                # HSTS (Strict-Transport-Security) : Force l'utilisation de HTTPS
                strict_transport_security:
                    max_age: 31536000
                    include_sub_domains: true

                # X-Frame-Options : Empêche l'utilisation dans des iframes (clickjacking)
                x_frame_options: 'DENY'

                # X-Content-Type-Options : Empêche les attaques de type MIME sniffing
                x_content_type_options: 'nosniff'

                # X-XSS-Protection : Activer la protection contre les attaques XSS
                x_xss_protection: '1; mode=block'

                # Content-Security-Policy (CSP) : Définit une politique de chargement de contenu
                content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self'; img-src 'self' data:;"

    access_control:
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_VETERINAIRE }
        - { path: ^/admin, roles: ROLE_EMPLOYE }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
