version: '3'
services:
  mongodb:
    image: mongo:7.0.12
    restart: always
    ports:
      - "8090:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: DbNameEcfZoo
      MONGO_INITDB_ROOT_PASSWORD: DbMotDePasse-2024-Ecf-ZooArcadia
      