controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index
    methods: ['GET', 'POST'] # Autorise les méthodes GET et POST pour cette route

app_formulaire:
    path: /formulaire
    controller: App\Controller\FormulaireController::index
    methods: ['GET', 'POST']

app_connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index
    methods: ['GET', 'POST']
