parameters:
    mongodb_server: '%env(MONGODB_SERVER)%'
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    App\Listeners\MyEventSubscriber:
        arguments:
            - '@doctrine_mongodb.odm.document_manager'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Listeners/'
            - '../src/Document/'
